env:
  browser: true
  node: true
extends:
  - standard-with-typescript
parserOptions:
  project: tsconfig.json
rules:
  comma-dangle:
    - error
    - always-multiline
overrides:
  - files: __tests__/**/*
    env:
      jest: true